### PR TITLE
Conditional setup, deepnets local predictions fallback and DataFrame support

### PR DESCRIPTION
**Pull request by mmerce**

### CODE REVIEW

**Comment by mmerce** [comment]
@charleslparker, I've updated the sensenet version, but I thought it would be good if we don't use it on Windows by default. I've added an enviroment variable that we can set to change that setting. Do you think that would help us overcome the issues in old Windows?

**Comment by charleslparker** [comment]
> Do you think that would help us overcome the issues in old Windows?

I mean, I guess the first goal is just not to fail for windows users when we try to install the bindings, yeah?  In this case, it sounds like that solves the problem.  We don't *need* sensenet for anything except image predictions.  I think it's fine if we just declare that we can't do those on Windows (at least until tensorflow support improves), and just fall back to the old code.

**Comment by mmerce** [comment]
> > Do you think that would help us overcome the issues in old Windows?
> 
> I mean, I guess the first goal is just not to fail for windows users when we try to install the bindings, yeah? In this case, it sounds like that solves the problem. We don't _need_ sensenet for anything except image predictions. I think it's fine if we just declare that we can't do those on Windows (at least until tensorflow support improves), and just fall back to the old code.

Yes, that's mostly it. By default, we would not install sensenet on Windows. We still would install it iff the user sets a BIGML_IMAGES_SUPPORT=1 environment variable before the install. That would cover the case where someone deals with the task of downloading the dlls needed for the build and wants to use images no matter what.

**Review by jaor — APPROVED** [review]
LGTM! :thumbsup:

**Pull request merged**
