### PR TITLE
README.rst: Add syntax highlighting

### PR DESCRIPTION
**Pull request by msabramo**
See at https://github.com/msabramo/python/blob/patch-1/README.rst

### CODE REVIEW

**Comment by mmerce** [comment]
Good idea. I think you missed the :: in

*You can then print the prediction using the pprint method::*
would you mind fixing that? I'd add your changes to the next branch waiting for a new version to be released.

You can keep changing that too anytime, if you feel like it, in the docs section. ;-)

**Comment by msabramo** [comment]
Updated.

**Comment by mmerce** [comment]
Added to next.

**Comment by mmerce** [comment]
Thank you for your contribution.

Cheers!

**Pull request closed without merging**
