### PR TITLE
Input datetimes in local predictions

### PR DESCRIPTION
**Pull request by unmonoqueteclea**
With this PR, the local models will accept raw datetime inputs.
Currently, it only works with models.
After this is reviewed, I will add the option to the rest of supervised-models

### CODE REVIEW

**Comment by unmonoqueteclea** [comment]
When requesting a model to apian with only_model=True,  datetime fields are not returned in the output, so I had to set it to False until this is fixed.

**Comment by unmonoqueteclea** [comment]
I tested all the unsupervised models but association discovery (association discovery didn't find any rule with the dates dataset used) although if one model works all the others should work in the same way

**Comment by unmonoqueteclea** [comment]
Finally added tests for all kinds of models. I think is ready for review @mmerce

**Comment by mmerce** [comment]
closing this PR to open a new one from bigmlcom

**Pull request closed without merging**
