### PR TITLE
Adding TOC to docs and improving 101's

### PR DESCRIPTION
**Pull request by mmerce**

### CODE REVIEW

**Comment by unmonoqueteclea** [comment]
Some tests should be run again. Please check, @mmerce

**Comment by mmerce** [comment]
@unmonoqueteclea , tests passed, but please wait till I add some improvements to the api.ok method

**Comment by mmerce** [comment]
@unmonoqueteclea, finally tests passed. Can you please merge, tag and publish?

**Comment by unmonoqueteclea** [comment]
`version.py` is not updated

**Pull request merged**
